# handler for adapter wavefront
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: testhandler
  namespace: istio-system
spec:
  adapter: wavefront
  connection:
    address: "{ADDRESS}" # replaced by the test at runtime
  params:
    domain: domain.wavefront.com
    token: api-token
    metrics:
    - name: requestsize.metric.istio-system
      type: COUNTER
---
# instance for template metric
apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: requestsize
  namespace: istio-system
spec:
  value: request.size | 0
  dimensions:
    source_service: source.service | "unknown"
    source_version: source.labels["version"] | "unknown"
    destination_service: destination.service | "unknown"
    destination_version: destination.labels["version"] | "unknown"
    response_code: response.code | 200
  monitored_resource_type: '"UNSPECIFIED"'
---
# rule to dispatch to handler h1
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: testrule
  namespace: istio-system
spec:
  actions:
  - handler: testhandler.istio-system
    instances:
    - requestsize.metric
---
