# handler for adapter wavefront
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: testhandler
  namespace: istio-system
spec:
  adapter: wavefront
  connection:
    address: "{ADDRESS}" # replaced by the test at runtime
  params:
    direct:
      domain: domain.wavefront.com
      token: api-token
    flush_interval:
      seconds: 5
    prefix: testprefix
    metrics:
    - name: requestsize.instance.istio-system
      type: COUNTER
---
# instance for template metric
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: requestsize
  namespace: istio-system
spec:
  template: metric
  params:
    value: request.size | 0
    dimensions:
      response_code: response.code | 200
    monitored_resource_type: '"UNSPECIFIED"'
---
# rule to dispatch to handler testhandler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: testrule
  namespace: istio-system
spec:
  actions:
  - handler: testhandler.istio-system
    instances:
    - requestsize
---
