# handler for adapter wavefront
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: wavefront-handler
  namespace: istio-system
spec:
  adapter: wavefront
  connection:
    address: "wavefront-adapter:8080"
  params:
    direct:
      server: server.wavefront.com
      token: api-token
    flushInterval: 5s
    prefix: "istio"
    metrics:
    - name: requestsize.instance.istio-system
      type: COUNTER
---
# instance for template metric
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: requestsize
  namespace: istio-system
spec:
  template: metric
  params:
    value: request.size | 0
    dimensions:
      response_code: response.code | 200
    monitored_resource_type: '"UNSPECIFIED"'
---
# rule to dispatch to handler wavefront-handler
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: wavefront-rule
  namespace: istio-system
spec:
  actions:
  - handler: wavefront-handler.istio-system
    instances:
    - requestsize
---
